name: Daily Financial Data Update

on:
  schedule:
    - cron: '05 6 * * *'  # 한국시간 14:45
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run your script
      run: |
        python securities_financial_status.py

    - name: Commit and push output file
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add financial_data.csv
        git commit -m "Update financial_data.csv from GitHub Actions" || echo "No changes to commit"
        git push
